// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { onehelpApiBlock } from './index'
import { auth } from './auth'

export const onehelpApiBlockSchema = parseBlockSchema(onehelpApiBlock)
export const onehelpApiCredentialsSchema = parseBlockCredentials(onehelpApiBlock.id, auth.schema)
